baseURL = 'http://metzgr.github.io/beta-performance-gov/'
defaultContentLanguage = "en"
title = 'Performance.gov'
theme = "pgov"

[outputFormats]
  # Ensure there are no custom settings here.

[outputs]
  # Ensure there are no custom settings here.